### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by RikuKawai** [TorontoCodingCollective/TorontoRobotFramework#2]
ChassisSubsystem.java and T_SrxEncoder.java both depend on a CTRE library which is not included in the project or referenced in any documentation.

Suggest including the jar file for this library inside the project and referencing it internally.

**Comment by richardemcmullin** [comment]
See "Adding the CTRE jars" here http://www.torontocodingcollective.com/installing-toronto-framework

**Comment by richardemcmullin** [comment]
We can put the jar in the project so that it is downloaded with the project setup.  Unfortunately the wpilib ant build expects the jar to be in {user_home}/wpilib/user/java/lib.
